/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author erlangga
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jconadokt = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtxtkewar = new javax.swing.JTextField();
        jtxtjenis = new javax.swing.JTextField();
        jtxtnama = new javax.swing.JTextField();
        jtxtusia = new javax.swing.JTextField();
        jtxtgol = new javax.swing.JTextField();
        jtxtstatus = new javax.swing.JTextField();
        jtxtwaktu = new javax.swing.JTextField();
        jtxtspesial = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jtxtalamat = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jconadokt.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jconadokt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Salah Satu --", "DR. FarrasYassar", "DR. Anisa Putri", "DR. Harun Fajar", " " }));
        jconadokt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jconadoktActionPerformed(evt);
            }
        });
        getContentPane().add(jconadokt);
        jconadokt.setBounds(179, 69, 130, 20);

        jLabel1.setText("Pilih Dokter");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(31, 72, 80, 14);

        jLabel3.setText("Nama");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(31, 139, 80, 14);

        jLabel4.setText("Alamat");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 170, 80, 14);

        jLabel5.setText("Usia");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 200, 70, 14);

        jLabel6.setText("Jenis Kelamin");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 230, 110, 20);

        jLabel7.setText("Golongan Darah");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 264, 120, 20);

        jLabel8.setText("Status");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 290, 100, 20);

        jLabel9.setText("Kewarganegaraan");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 380, 120, 14);

        jLabel10.setText("Waktu Praktek");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 320, 110, 14);

        jLabel11.setText("Dokter Spesialis");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 350, 110, 14);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("PEMILIHAN DOKTER");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(70, 20, 260, 20);

        jtxtkewar.setEditable(false);
        jtxtkewar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtxtkewar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtkewarActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtkewar);
        jtxtkewar.setBounds(180, 380, 180, 19);

        jtxtjenis.setEditable(false);
        jtxtjenis.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtxtjenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtjenisActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtjenis);
        jtxtjenis.setBounds(180, 230, 180, 19);

        jtxtnama.setEditable(false);
        jtxtnama.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtxtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnamaActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtnama);
        jtxtnama.setBounds(180, 140, 180, 20);

        jtxtusia.setEditable(false);
        jtxtusia.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtxtusia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtusiaActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtusia);
        jtxtusia.setBounds(180, 200, 180, 19);

        jtxtgol.setEditable(false);
        jtxtgol.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtxtgol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtgolActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtgol);
        jtxtgol.setBounds(180, 260, 180, 19);

        jtxtstatus.setEditable(false);
        jtxtstatus.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtxtstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtstatusActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtstatus);
        jtxtstatus.setBounds(180, 290, 180, 19);

        jtxtwaktu.setEditable(false);
        jtxtwaktu.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtxtwaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtwaktuActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtwaktu);
        jtxtwaktu.setBounds(180, 320, 180, 20);

        jtxtspesial.setEditable(false);
        jtxtspesial.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtxtspesial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtspesialActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtspesial);
        jtxtspesial.setBounds(180, 350, 180, 19);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Identitas"));
        jPanel1.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(null);

        jtxtalamat.setEditable(false);
        jtxtalamat.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtxtalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtalamatActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtalamat);
        jtxtalamat.setBounds(170, 70, 180, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 100, 370, 310);

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 10, 400, 440);

        setBounds(0, 0, 416, 490);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtkewarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtkewarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtkewarActionPerformed

    private void jtxtjenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtjenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtjenisActionPerformed

    private void jtxtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnamaActionPerformed

    private void jtxtusiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtusiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtusiaActionPerformed

    private void jtxtgolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtgolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtgolActionPerformed

    private void jtxtstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtstatusActionPerformed

    private void jtxtwaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtwaktuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtwaktuActionPerformed

    private void jtxtspesialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtspesialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtspesialActionPerformed

    private void jconadoktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jconadoktActionPerformed

        if (jconadokt.getSelectedItem().equals("DR. FarrasYassar")) {

            jtxtnama.setText("DR. Farras Yassar ");

            jtxtalamat.setText("Jl. Surabaya 16, Malang");

            jtxtusia.setText("20 Tahun");

            jtxtjenis.setText("Laki-Laki");

            jtxtgol.setText("A");

            jtxtstatus.setText("Belum Menikah ");

            jtxtkewar.setText("Indonesia");

            jtxtspesial.setText("Dokter Umum");

            jtxtwaktu.setText(" Pagi (07.00-15.00)");

        } else if (jconadokt.getSelectedItem().equals("DR. Anisa Putri")) {

            jtxtnama.setText("DR. Anisa Putri");

            jtxtalamat.setText("Jl. Veteran 3, Malang");

            jtxtusia.setText("20 Tahun");

            jtxtjenis.setText("Perempuan");

            jtxtgol.setText("O");

            jtxtstatus.setText("Belum Menikah");

            jtxtkewar.setText("Indonesia");

            jtxtspesial.setText("Dokter Gigi");

            jtxtwaktu.setText(" Sore (16.00-22.00)");

        }
        else {
if(jconadokt.getSelectedItem().equals("DR. Harun Fajar")){

jtxtnama.setText("DR. Harun Fajar ");

jtxtalamat.setText("Jl. Bandung 9, Malang");

jtxtusia.setText("20 Tahun");

jtxtjenis.setText("Laki-Laki");

jtxtgol.setText("B");

jtxtstatus.setText("Belum Menikah");

jtxtkewar.setText("Indonesia");

jtxtspesial.setText("Dokter Gizi");

jtxtwaktu.setText(" Malam (22.00-06.00)");

}
                }

// TODO add your handling code here:
    }//GEN-LAST:event_jconadoktActionPerformed

    private void jtxtalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtalamatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jconadokt;
    private javax.swing.JTextField jtxtalamat;
    private javax.swing.JTextField jtxtgol;
    private javax.swing.JTextField jtxtjenis;
    private javax.swing.JTextField jtxtkewar;
    private javax.swing.JTextField jtxtnama;
    private javax.swing.JTextField jtxtspesial;
    private javax.swing.JTextField jtxtstatus;
    private javax.swing.JTextField jtxtusia;
    private javax.swing.JTextField jtxtwaktu;
    // End of variables declaration//GEN-END:variables
}
